Solve crash
alicevision/QtAliceVision pull request #23
Opened 2022-05-10 14:35 UTC by servantftechnicolor

Aynschronous loading will lead to a random crash because the indices array may not have been filled

2022-05-10 14:51 UTC, simogasp requested changes

2022-05-10 14:51 UTC, simogasp commented on src/Surface.cpp
> +            double cy = y - center(1);
```suggestion
            const double cx = x - center(0);
            const double cy = y - center(1);
```

2022-05-10 14:51 UTC, simogasp commented on src/Surface.cpp
> +            double dist = sqrt(cx * cx + cy * cy);
```suggestion
            const double dist = std:: hypot(cx, cy);
```

2022-05-10 14:51 UTC, simogasp commented on src/Surface.cpp
> +        if (i + 2 >= _indices.size()) continue;
maybe `break`? Or the vector can increase in size meanwhile?

2022-06-01 12:24 UTC, fabiencastan approved these changes

2022-06-03 20:58 UTC, merged