[Features Viewer] Track reconstruction states
alicevision/QtAliceVision pull request #25
Opened 2022-10-20 10:39 UTC by mugulmd

## Description

This PR introduces 3 "reconstruction states" for tracks: 
- 0: no feature on the track has been reconstructed
- 1: at least one feature on the track has been reconstructed
- 2: all features on the track have been reconstructed.

> Note: by *reconstructed* we mean that the feature has a corresponding landmark

These states are visualized with a simple color code (one color per state, defined in the `_trackReconstructionColors` field of `FeaturesViewer`).

Their purpose is to convey a *global* information to the user about the track, and thus avoid redundancy with the points drawn on the track, which already provide a *local* information about the reconstruction.

2022-12-07 17:25 UTC, gregoire-dl requested changes

2022-12-07 17:25 UTC, gregoire-dl commented on src/MFeatures.hpp
> +      int reconstructionState() const
Using an enum "reconstructionState" instead of an int will I think improve readability.

2022-12-07 17:25 UTC, gregoire-dl commented on src/MFeatures.cpp
> +  bool updated = updateFromTracks(viewFeaturesPerViewPerDesc) && updateFromSfM(viewFeaturesPerViewPerDesc);
`updateFromTracks` and `updateFromSfM` should not block the extrated features display.
Extracted features should be visible even if StructureFromMotion is not computed.

2022-12-07 17:25 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +    geometryTrackLine[2]->setLineWidth(5.0f);
Note: the last call to the function `setLineWidth` seems to affect all the line width of the 3D Viewer as well.
Something to fix here or in Meshroom 3D Viewer.

2022-12-07 17:25 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +                setVertex(verticesEndpoints, vIdx + i, prevPoint + tr.map(triangle[i]), _endpointColor);
Track begin/end points can be drawn first in order to avoid missing tracks/points behind them.

2022-12-07 17:25 UTC, gregoire-dl commented on src/FeaturesViewer.hpp
> +      Q_PROPERTY(bool displayTrackEndpoints MEMBER _displayTrackEndpoints NOTIFY displayTrackEndpointsChanged)
It would be great to add a display option to draw only the tracks that include the current frame.

2023-01-18 09:27 UTC, mugulmd commented
Retested after rebase on develop with several datasets and camera tracking pipelines, seems to work fine

2023-01-30 15:13 UTC, gregoire-dl commented on src/MFeatures.cpp
> +        MGlobalTrackInfo& info = _globalTrackInfoPerTrack[trackId];
trackId type should be aliceVision::IndexT

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +    int vertexCount = params.nbFeaturesToDraw * kFeatVertices;
mix types std::size_t and int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +    int indexCount = params.nbFeaturesToDraw * kFeatIndices;
mix types std::size_t and int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryEndpoint = appendChildGeometry(node, nbEndpointsToDraw);
cast nbEndpointsToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryHighlightPoint = appendChildGeometry(node, nbHighlightPointsToDraw);
cast nbHighlightPointsToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +        geometryTrackLine[idx] = appendChildGeometry(node, nbTrackLinesToDraw[idx] * kLineVertices);
cast nbTrackLinesToDraw[idx] * kLineVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryReprojectionErrorLine = appendChildGeometry(node, nbReprojectionErrorLinesToDraw * kLineVertices);
cast nbReprojectionErrorLinesToDraw * kLineVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryPoint = appendChildGeometry(node, nbPointsToDraw);
cast nbPointsToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryEndpoint = getCleanChildGeometry(node, 1, nbEndpointsToDraw * kTriangleVertices);
cast nbEndpointsToDraw * kTriangleVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryHighlightPoint = getCleanChildGeometry(node, 2, nbHighlightPointsToDraw);
cast nbHighlightPointsToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +        geometryTrackLine[idx] = getCleanChildGeometry(node, idx+3, nbTrackLinesToDraw[idx] * kLineVertices);
cast idx+3 to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryReprojectionErrorLine = getCleanChildGeometry(node, 6, nbReprojectionErrorLinesToDraw * kLineVertices);
cast nbReprojectionErrorLinesToDraw * kLineVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryPoint = getCleanChildGeometry(node, 7, nbPointsToDraw);
cast nbPointsToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +        float angle = QLineF(pointFrom, pointTo).angle() - rotation();
cast QLineF(pointFrom, pointTo).angle() - rotation() to float

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +        const int vIdx = nbEndpointsDrawn * kTriangleVertices;
cast nbEndpointsDrawn * kTriangleVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +        for (int i = 0; i < kTriangleVertices; i++)
comparison of integer expressions of different signedness

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +            setVertex(verticesEndpoints, vIdx + i, pointFrom + tr.map(triangle[i]), color);
cast vIdx + i to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryPoint = appendChildGeometry(node, params.nbMatchesToDraw);
cast params.nbMatchesToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryPoint = getCleanChildGeometry(node, 8, params.nbMatchesToDraw);
cast params.nbMatchesToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryLine = appendChildGeometry(node, params.nbLandmarksToDraw * kReprojectionVertices);
cast params.nbLandmarksToDraw * kReprojectionVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryPoint = appendChildGeometry(node, params.nbLandmarksToDraw);
cast params.nbLandmarksToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryLine = getCleanChildGeometry(node, 9, params.nbLandmarksToDraw * kReprojectionVertices);
cast params.nbLandmarksToDraw * kReprojectionVertices to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +      geometryPoint = getCleanChildGeometry(node, 10, params.nbLandmarksToDraw);
cast params.nbLandmarksToDraw to int

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> +    vertices[idx].set(point.x(), point.y(), c.red(), c.green(), c.blue(), c.alpha());
cast qreal point.x() & point.y() to float
cast c.red() & c.green() & c.blue() & c.alpha() to uchar

2023-01-30 15:13 UTC, gregoire-dl commented on src/FeaturesViewer.cpp
> -      const QColor rc = c.darker(150); // darken the color to avoid confusion with track lines
reprojection error line color should be darker to avoid confusion with track lines

2023-01-30 15:13 UTC, gregoire-dl commented on src/MFeatures.cpp
> +void MFeatures::updateGlobalTrackInfo(MViewFeaturesPerViewPerDesc* viewFeaturesPerViewPerDesc)
Note:

Global track information needs a lot of I/O, memory and computation (all features, all tracks, ...).
Currently it's the only way to do it, I think.
Maybe, later on, we can compute & export this global information as an output JSON file of the SfM.

2023-02-01 14:06 UTC, gregoire-dl approved these changes

2023-02-14 18:34 UTC, fabiencastan commented on src/MFeatures.cpp
> +  const aliceVision::sfmData::SfMData& sfmData = _msfmData->rawData();
viewIdsToLoad.reserve(viewIdsToLoad.size() + sfmData.getViews().size())

2023-02-14 18:38 UTC, merged