[QmlSfmData] Handle exceptions and do not attempt to load invalid files
alicevision/QtAliceVision pull request #49
Opened 2023-10-26 16:09 UTC by cbentejac

This PR addresses 3 issues:
1. If a file that contained something other than an SfMData was provided to the SfmDataEntity, an unhandled exception was raised and led to a crash. That exception is now caught, and an error message printed.
2. If a file that contained either no or an empty SfMData file was provided, the SfmDataEntity was still attempting to create all the 3D components to display it, and the status was always set to `Ready` no matter what. With this PR, if the SfMData remains uninitialized (that might be the case if an exception from (1) is thrown), no 3D component is created and the status is set to `Error`. 
3. If a valid SfMData file contains no 3D information, the behaviour was the same as in (2), and the SfmDataEntity ended up loading and setting everything up although there was nothing to display. The lack of 3D info is now detected prior to creating and setting up all the 3D components. The status is also set to `Error`.

2023-10-26 16:39 UTC, fabiencastan requested changes

2023-10-26 16:39 UTC, fabiencastan commented on src/qmlSfmData/SfmDataEntity.cpp
> +    else if (sfmData.getLandmarks().empty())
sfmData.getLandmarks().empty() && camera poses are also empty

2023-10-26 17:36 UTC, cbentejac commented on src/qmlSfmData/SfmDataEntity.cpp
> +    else if (sfmData.getLandmarks().empty())
Done.

2023-10-27 10:29 UTC, fabiencastan approved these changes

2023-10-27 10:29 UTC, merged